[package]
name = "socialgirls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.27"
tokio = { version = "1.29.1", features = ["full"] }
webdriver = "0.48.0"
selenium-rs = "0.1.2"